amcl:
  ros__parameters:
    # Overall filter parameters

    min_particles: 100  # 100, Minimum allowed number of particles.
    max_particles: 500 #750  # 5000, Maximum allowed number of particles.
    pf_err: 0.01  # 0.01, Maximum error between the true distribution and the estimated distribution.
    pf_z: 0.99  # 0.99, Upper standard normal quantile for (1 - p), where p is the probability that the error on the estimated distrubition will be less than kld_err.

    update_min_d: 0.025  # 0.2, Translational movement required before performing a filter update.
    update_min_a: 0.05  # 0.5236 (π/6.0), Rotational movement required before performing a filter update.
    resample_interval: 3  # 2, Number of filter updates required before resampling.
    transform_tolerance: 0.5  # 1.0, Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.
    recovery_alpha_slow: 0.0  # 0.0, Exponential decay rate for the slow average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.001.
    recovery_alpha_fast: 0.0  # 0.0, Exponential decay rate for the fast average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.1.

    always_reset_initial_pose: false  # false, Requires that AMCL is provided an initial pose either via topic or initial_pose* parameter (with parameter set_initial_pose: true) when reset. Otherwise, by default AMCL will use the last known pose to initialize.
    set_initial_pose: true  # false, Causes AMCL to set initial pose from the initial_pose* parameters instead of waiting for the initial_pose message.

    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    # initial_pose_x: 0.0  # 0.0, Initial pose mean, used to initialize filter with Gaussian distribution.
    # initial_pose_y: 0.0  # 0.0, Initial pose mean (y), used to initialize filter with Gaussian distribution.
    # initial_pose_a: 0.0  # 0.0, Initial pose mean (yaw), used to initialize filter with Gaussian distribution.
    # initial_cov_xx: 0.25  # 0.25, Initial pose covariance (x*x), used to initialize filter with Gaussian distribution.
    # initial_cov_yy: 0.25  # 0.25, Initial pose covariance (y*y), used to initialize filter with Gaussian distribution.
    # initial_cov_aa: 0.06854  # (π/12)*(π/12), Initial pose covariance (yaw*yaw), used to initialize filter with Gaussian distribution.

    save_pose_rate: 0.5  # 0.5, Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server, in the variables ~initial_pose_* and ~initial_cov_*. This saved pose will be used on subsequent runs to initialize the filter. -1.0 to disable.
    first_map_only: false  # false, When set to true, AMCL will only use the first map it subscribes to, rather than updating each time a new one is received.
    map_topic: /map

    # laser model parameters

    laser_min_range: -1.0  # -1.0, Minimum scan range to be considered; -1.0 will cause the laser's reported minimum range to be used.
    laser_max_range: -1.0  # -1.0, Maximum scan range to be considered; -1.0 will cause the laser's reported maximum range to be used.
    max_beams: 180  # 30, How many evenly-spaced beams in each scan to be used when updating the filter.
    z_hit: 0.95  # 0.95, Mixture weight for the z_hit part of the model.
    z_short: 0.01  # 0.1, Mixture weight for the z_short part of the model.
    z_max: 0.01  # 0.05, Mixture weight for the z_max part of the model.
    z_rand: 0.01  # 0.05, Mixture weight for the z_rand part of the model.
    sigma_hit: 0.1  # 0.2, Standard deviation for Gaussian model used in z_hit part of the model.
    lambda_short: 0.1  # 0.1, Exponential decay parameter for z_short part of model.
    laser_likelihood_max_dist: 12.0  # 2.0, Maximum distance to do obstacle inflation on map, for use in likelihood_field model.
    laser_model_type: likelihood_field  # likelihood_field, Which model to use, either beam, likelihood_field, or likelihood_field_prob (same as likelihood_field but incorporates the beamskip feature, if enabled).

    # Odometry model parameters

    robot_model_type: nav2_amcl::DifferentialMotionModel  # The fully-qualified type of the plugin class. Options are "nav2_amcl::DifferentialMotionModel" and "nav2_amcl::OmniMotionModel". Users can also provide their own custom motion model plugin type.

    # translation std dev, m
    alpha1: 0.15  # 0.2, Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
    alpha2: 0.15  # 0.2, Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
    alpha3: 0.15  # 0.2, Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
    alpha4: 0.15  # 0.2, Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.
    alpha5: 0.05  # 0.2, Translation-related noise parameter (only used if model is "omni").

    base_frame_id: base_link  # base_link, Which frame to use for the robot base
    odom_frame_id: odom  # odom, Which frame to use for odometry.
    global_frame_id: map  # map, The name of the coordinate frame published by the localization system
    tf_broadcast: true  # true, Set this to false to prevent amcl from publishing the transform between the global frame and the odometry frame.

    scan_topic: /scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

behavior_server:
  ros__parameters:
    use_sim_time: False
#    behavior_plugins: ["spin", "my_spin", "backup", "wait"]
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"

#    my_spin:
#      plugin: "my_nav2_behaviors::MySpinBehavior"

    backup:
      plugin: "nav2_behaviors/BackUp"

    wait:
      plugin: "nav2_behaviors/Wait"


bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 20
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    #default_bt_xml_filename: "/home/pi/amr_configs/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/home/pi/amr_configs/navigate_to_pose_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False
    transform_tolerance: 0.5

/controller_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    FollowPath:
      allow_reversing: false
      angular_disengage_threshold: 0.785
      angular_dist_threshold: 0.785
      approach_velocity_scaling_dist: 0.6
      closed_loop: true
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0
      desired_linear_vel: 0.40
      forward_sampling_distance: 0.5
      inflation_cost_scaling_factor: 3.0
      lookahead_dist: 0.3
      lookahead_time: 1.5
      max_allowed_time_to_collision_up_to_carrot: 1.0
      max_angular_accel: 1.6
      max_lookahead_dist: 0.5
      max_robot_pose_search_dist: 10.0
      min_approach_linear_velocity: 0.20 #0.02
      min_lookahead_dist: 0.3
      plugin: nav2_rotation_shim_controller::RotationShimController
      primary_controller: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.2
      rotate_to_goal_heading: true
      rotate_to_heading_angular_vel: 0.5
      rotate_to_heading_min_angle: 0.3
      simulate_ahead_time: 1.0
      transform_tolerance: 0.5
      use_collision_detection: true
      use_cost_regulated_linear_velocity_scaling: true
      use_interpolation: true
      use_regulated_linear_velocity_scaling: true
      use_rotate_to_heading: true
      use_velocity_scaled_lookahead_dist: false
    controller_frequency: 10.0
    controller_plugins:
    - FollowPath
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    odom_topic: odom
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.2
    progress_checker_plugin: progress_checker
    speed_limit_topic: speed_limit
    use_sim_time: false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False
    transform_tolerance: 1.0
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.09
      transform_tolerance: 1.0
      plugins: ["voxel2d_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0


        inflation_radius: 0.15
      voxel2d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan base_scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          observation_persistence: 0.5 
          clearing: True
          marking: True
          data_type: "LaserScan"
        base_scan:
          topic: /base/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters: 
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.08
      resolution: 0.05
      transform_tolerance: 1.0
      track_unknown_space: true
      plugins: ["static_layer", "voxel2d_layer", "voxel3d_layer", "inflation_layer"]
      voxel2d_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan base_scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          observation_persistence: 0.5 
          clearing: True
          marking: True
          data_type: "LaserScan"
        base_scan:
          topic: /base/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: realsense zed
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0 
        realsense:
          topic: /camera/depth/color/points
          raytrace_min_range: 0.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
        zed:
          topic: /zed/point_cloud/cloud_registered
          raytrace_min_range: 0.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.15
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/pi/amr_config/maps/house1.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    transform_tolerance: 1.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 2.0
    min_rotational_vel: 1.0
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

#velocity_smoother:
#  ros__parameters:
#    smoothing_frequency: 6.0
#    scale_velocities: false
#    feedback: "CLOSED_LOOP"
#    max_velocity: [0.25, 0.0, 2.0]
#    min_velocity: [0.0, 0.0, 0.0]
#    deadband_velocity: [0.0, 0.0, 0.0]
#    velocity_timeout: 1.0
#    max_accel: [2.5, 0.0, 3.2]
#    max_decel: [-2.5, 0.0, -3.2]
#    odom_topic: "odom"
#    odom_duration: 0.1
#    use_realtime_priority: false
#    enable_stamped_cmd_vel: false
